package pe.com.devteam.dao;

import java.util.List;
import pe.com.devteam.bean.Email;
import pe.com.devteam.bean.EmailCriteria;

public interface EmailDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	int countByExample(EmailCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	int deleteByExample(EmailCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	void insert(Email record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	void insertSelective(Email record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	List<Email> selectByExample(EmailCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	Email selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Email record, EmailCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	int updateByExample(Email record, EmailCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Email record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Email record);
}