package pe.com.devteam.bean;

import java.util.Date;

public class Business {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column business.id
	 * @ibatorgenerated
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column business.name
	 * @ibatorgenerated
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column business.description
	 * @ibatorgenerated
	 */
	private String description;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column business.state
	 * @ibatorgenerated
	 */
	private Integer state;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column business.created_at
	 * @ibatorgenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column business.updated_at
	 * @ibatorgenerated
	 */
	private Date updatedAt;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column business.id
	 * @return  the value of business.id
	 * @ibatorgenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column business.id
	 * @param id  the value for business.id
	 * @ibatorgenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column business.name
	 * @return  the value of business.name
	 * @ibatorgenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column business.name
	 * @param name  the value for business.name
	 * @ibatorgenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column business.description
	 * @return  the value of business.description
	 * @ibatorgenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column business.description
	 * @param description  the value for business.description
	 * @ibatorgenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column business.state
	 * @return  the value of business.state
	 * @ibatorgenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column business.state
	 * @param state  the value for business.state
	 * @ibatorgenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column business.created_at
	 * @return  the value of business.created_at
	 * @ibatorgenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column business.created_at
	 * @param createdAt  the value for business.created_at
	 * @ibatorgenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column business.updated_at
	 * @return  the value of business.updated_at
	 * @ibatorgenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column business.updated_at
	 * @param updatedAt  the value for business.updated_at
	 * @ibatorgenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table business
	 * @ibatorgenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof Business)) {
			return false;
		}
		Business other = (Business) that;
		return this.getId() == null ? other == null
				: this.getId().equals(other.getId()) && this.getName() == null ? other == null
						: this.getName().equals(other.getName()) && this.getDescription() == null ? other == null
								: this.getDescription().equals(other.getDescription()) && this.getState() == null
										? other == null
										: this.getState().equals(other.getState()) && this.getCreatedAt() == null
												? other == null
												: this.getCreatedAt().equals(other.getCreatedAt())
														&& this.getUpdatedAt() == null ? other == null
																: this.getUpdatedAt().equals(other.getUpdatedAt());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table business
	 * @ibatorgenerated
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getName() != null) {
			hash *= getName().hashCode();
		}
		if (getDescription() != null) {
			hash *= getDescription().hashCode();
		}
		if (getState() != null) {
			hash *= getState().hashCode();
		}
		if (getCreatedAt() != null) {
			hash *= getCreatedAt().hashCode();
		}
		if (getUpdatedAt() != null) {
			hash *= getUpdatedAt().hashCode();
		}
		return hash;
	}
}