package pe.com.devteam.bean;

import java.util.Date;

public class Campaign {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.id
	 * @ibatorgenerated
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.name
	 * @ibatorgenerated
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.mail_send
	 * @ibatorgenerated
	 */
	private String mailSend;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.subject
	 * @ibatorgenerated
	 */
	private String subject;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.total_mail
	 * @ibatorgenerated
	 */
	private Integer totalMail;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.company_id
	 * @ibatorgenerated
	 */
	private Integer companyId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.business_id
	 * @ibatorgenerated
	 */
	private Integer businessId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.state
	 * @ibatorgenerated
	 */
	private Integer state;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.created_at
	 * @ibatorgenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.updated_at
	 * @ibatorgenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column campaigns.message
	 * @ibatorgenerated
	 */
	private String message;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.id
	 * @return  the value of campaigns.id
	 * @ibatorgenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.id
	 * @param id  the value for campaigns.id
	 * @ibatorgenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.name
	 * @return  the value of campaigns.name
	 * @ibatorgenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.name
	 * @param name  the value for campaigns.name
	 * @ibatorgenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.mail_send
	 * @return  the value of campaigns.mail_send
	 * @ibatorgenerated
	 */
	public String getMailSend() {
		return mailSend;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.mail_send
	 * @param mailSend  the value for campaigns.mail_send
	 * @ibatorgenerated
	 */
	public void setMailSend(String mailSend) {
		this.mailSend = mailSend;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.subject
	 * @return  the value of campaigns.subject
	 * @ibatorgenerated
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.subject
	 * @param subject  the value for campaigns.subject
	 * @ibatorgenerated
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.total_mail
	 * @return  the value of campaigns.total_mail
	 * @ibatorgenerated
	 */
	public Integer getTotalMail() {
		return totalMail;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.total_mail
	 * @param totalMail  the value for campaigns.total_mail
	 * @ibatorgenerated
	 */
	public void setTotalMail(Integer totalMail) {
		this.totalMail = totalMail;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.company_id
	 * @return  the value of campaigns.company_id
	 * @ibatorgenerated
	 */
	public Integer getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.company_id
	 * @param companyId  the value for campaigns.company_id
	 * @ibatorgenerated
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.business_id
	 * @return  the value of campaigns.business_id
	 * @ibatorgenerated
	 */
	public Integer getBusinessId() {
		return businessId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.business_id
	 * @param businessId  the value for campaigns.business_id
	 * @ibatorgenerated
	 */
	public void setBusinessId(Integer businessId) {
		this.businessId = businessId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.state
	 * @return  the value of campaigns.state
	 * @ibatorgenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.state
	 * @param state  the value for campaigns.state
	 * @ibatorgenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.created_at
	 * @return  the value of campaigns.created_at
	 * @ibatorgenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.created_at
	 * @param createdAt  the value for campaigns.created_at
	 * @ibatorgenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.updated_at
	 * @return  the value of campaigns.updated_at
	 * @ibatorgenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.updated_at
	 * @param updatedAt  the value for campaigns.updated_at
	 * @ibatorgenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column campaigns.message
	 * @return  the value of campaigns.message
	 * @ibatorgenerated
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column campaigns.message
	 * @param message  the value for campaigns.message
	 * @ibatorgenerated
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table campaigns
	 * @ibatorgenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof Campaign)) {
			return false;
		}
		Campaign other = (Campaign) that;
		return this.getId() == null ? other == null
				: this.getId().equals(other.getId()) && this.getName() == null ? other == null
						: this.getName().equals(other.getName()) && this.getMailSend() == null ? other == null
								: this.getMailSend().equals(other.getMailSend()) && this.getSubject() == null
										? other == null
										: this.getSubject().equals(other.getSubject()) && this.getTotalMail() == null
												? other == null
												: this.getTotalMail().equals(other.getTotalMail())
														&& this.getCompanyId() == null
																? other == null
																: this.getCompanyId().equals(other.getCompanyId())
																		&& this.getBusinessId() == null
																				? other == null
																				: this.getBusinessId()
																						.equals(other.getBusinessId())
																						&& this.getState() == null
																								? other == null
																								: this.getState()
																										.equals(other
																												.getState())
																										&& this.getCreatedAt() == null
																												? other == null
																												: this.getCreatedAt()
																														.equals(other
																																.getCreatedAt())
																														&& this.getUpdatedAt() == null
																																? other == null
																																: this.getUpdatedAt()
																																		.equals(other
																																				.getUpdatedAt())
																																		&& this.getMessage() == null
																																				? other == null
																																				: this.getMessage()
																																						.equals(other
																																								.getMessage());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table campaigns
	 * @ibatorgenerated
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getName() != null) {
			hash *= getName().hashCode();
		}
		if (getMailSend() != null) {
			hash *= getMailSend().hashCode();
		}
		if (getSubject() != null) {
			hash *= getSubject().hashCode();
		}
		if (getTotalMail() != null) {
			hash *= getTotalMail().hashCode();
		}
		if (getCompanyId() != null) {
			hash *= getCompanyId().hashCode();
		}
		if (getBusinessId() != null) {
			hash *= getBusinessId().hashCode();
		}
		if (getState() != null) {
			hash *= getState().hashCode();
		}
		if (getCreatedAt() != null) {
			hash *= getCreatedAt().hashCode();
		}
		if (getUpdatedAt() != null) {
			hash *= getUpdatedAt().hashCode();
		}
		if (getMessage() != null) {
			hash *= getMessage().hashCode();
		}
		return hash;
	}
}