package pe.com.devteam.bean;

import java.util.Date;

public class Email {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column emails.id
	 * @ibatorgenerated
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column emails.mail
	 * @ibatorgenerated
	 */
	private String mail;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column emails.company_id
	 * @ibatorgenerated
	 */
	private Integer companyId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column emails.business_id
	 * @ibatorgenerated
	 */
	private Integer businessId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column emails.state
	 * @ibatorgenerated
	 */
	private Integer state;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column emails.created_at
	 * @ibatorgenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column emails.updated_at
	 * @ibatorgenerated
	 */
	private Date updatedAt;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column emails.id
	 * @return  the value of emails.id
	 * @ibatorgenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column emails.id
	 * @param id  the value for emails.id
	 * @ibatorgenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column emails.mail
	 * @return  the value of emails.mail
	 * @ibatorgenerated
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column emails.mail
	 * @param mail  the value for emails.mail
	 * @ibatorgenerated
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column emails.company_id
	 * @return  the value of emails.company_id
	 * @ibatorgenerated
	 */
	public Integer getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column emails.company_id
	 * @param companyId  the value for emails.company_id
	 * @ibatorgenerated
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column emails.business_id
	 * @return  the value of emails.business_id
	 * @ibatorgenerated
	 */
	public Integer getBusinessId() {
		return businessId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column emails.business_id
	 * @param businessId  the value for emails.business_id
	 * @ibatorgenerated
	 */
	public void setBusinessId(Integer businessId) {
		this.businessId = businessId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column emails.state
	 * @return  the value of emails.state
	 * @ibatorgenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column emails.state
	 * @param state  the value for emails.state
	 * @ibatorgenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column emails.created_at
	 * @return  the value of emails.created_at
	 * @ibatorgenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column emails.created_at
	 * @param createdAt  the value for emails.created_at
	 * @ibatorgenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column emails.updated_at
	 * @return  the value of emails.updated_at
	 * @ibatorgenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column emails.updated_at
	 * @param updatedAt  the value for emails.updated_at
	 * @ibatorgenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof Email)) {
			return false;
		}
		Email other = (Email) that;
		return this.getId() == null ? other == null
				: this.getId().equals(other.getId()) && this.getMail() == null ? other == null
						: this.getMail().equals(other.getMail()) && this.getCompanyId() == null ? other == null
								: this.getCompanyId().equals(other.getCompanyId()) && this.getBusinessId() == null
										? other == null
										: this.getBusinessId().equals(other.getBusinessId()) && this.getState() == null
												? other == null
												: this.getState().equals(other.getState())
														&& this.getCreatedAt() == null
																? other == null
																: this.getCreatedAt().equals(other.getCreatedAt())
																		&& this.getUpdatedAt() == null ? other == null
																				: this.getUpdatedAt()
																						.equals(other.getUpdatedAt());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table emails
	 * @ibatorgenerated
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getMail() != null) {
			hash *= getMail().hashCode();
		}
		if (getCompanyId() != null) {
			hash *= getCompanyId().hashCode();
		}
		if (getBusinessId() != null) {
			hash *= getBusinessId().hashCode();
		}
		if (getState() != null) {
			hash *= getState().hashCode();
		}
		if (getCreatedAt() != null) {
			hash *= getCreatedAt().hashCode();
		}
		if (getUpdatedAt() != null) {
			hash *= getUpdatedAt().hashCode();
		}
		return hash;
	}
}