package pe.com.devteam.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.com.devteam.bean.Business;
import pe.com.devteam.bean.BusinessCriteria;
import pe.com.devteam.dao.BusinessDAO;

public class BusinessDAOImpl extends SqlMapClientDaoSupport implements BusinessDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public BusinessDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public int countByExample(BusinessCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("business.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public int deleteByExample(BusinessCriteria example) {
        int rows = getSqlMapClientTemplate().delete("business.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Business key = new Business();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("business.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public void insert(Business record) {
        getSqlMapClientTemplate().insert("business.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public void insertSelective(Business record) {
        getSqlMapClientTemplate().insert("business.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Business> selectByExample(BusinessCriteria example) {
        List<Business> list = getSqlMapClientTemplate().queryForList("business.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public Business selectByPrimaryKey(Integer id) {
        Business key = new Business();
        key.setId(id);
        Business record = (Business) getSqlMapClientTemplate().queryForObject("business.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Business record, BusinessCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("business.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public int updateByExample(Business record, BusinessCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("business.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Business record) {
        int rows = getSqlMapClientTemplate().update("business.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Business record) {
        int rows = getSqlMapClientTemplate().update("business.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table business
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends BusinessCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, BusinessCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}