package pe.com.devteam.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.com.devteam.bean.Campaign;
import pe.com.devteam.bean.CampaignCriteria;
import pe.com.devteam.dao.CampaignDAO;

public class CampaignDAOImpl extends SqlMapClientDaoSupport implements CampaignDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public CampaignDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int countByExample(CampaignCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("campaigns.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int deleteByExample(CampaignCriteria example) {
        int rows = getSqlMapClientTemplate().delete("campaigns.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Campaign key = new Campaign();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("campaigns.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public void insert(Campaign record) {
        getSqlMapClientTemplate().insert("campaigns.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public void insertSelective(Campaign record) {
        getSqlMapClientTemplate().insert("campaigns.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Campaign> selectByExampleWithBLOBs(CampaignCriteria example) {
        List<Campaign> list = getSqlMapClientTemplate().queryForList("campaigns.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Campaign> selectByExampleWithoutBLOBs(CampaignCriteria example) {
        List<Campaign> list = getSqlMapClientTemplate().queryForList("campaigns.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public Campaign selectByPrimaryKey(Integer id) {
        Campaign key = new Campaign();
        key.setId(id);
        Campaign record = (Campaign) getSqlMapClientTemplate().queryForObject("campaigns.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Campaign record, CampaignCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("campaigns.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int updateByExampleWithBLOBs(Campaign record, CampaignCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("campaigns.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int updateByExampleWithoutBLOBs(Campaign record, CampaignCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("campaigns.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Campaign record) {
        int rows = getSqlMapClientTemplate().update("campaigns.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeyWithBLOBs(Campaign record) {
        int rows = getSqlMapClientTemplate().update("campaigns.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeyWithoutBLOBs(Campaign record) {
        int rows = getSqlMapClientTemplate().update("campaigns.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table campaigns
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends CampaignCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, CampaignCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}