package pe.com.devteam.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.com.devteam.bean.Company;
import pe.com.devteam.bean.CompanyCriteria;
import pe.com.devteam.dao.CompanyDAO;

public class CompanyDAOImpl extends SqlMapClientDaoSupport implements CompanyDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public CompanyDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public int countByExample(CompanyCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("companies.ibatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public int deleteByExample(CompanyCriteria example) {
		int rows = getSqlMapClientTemplate().delete("companies.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Company key = new Company();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("companies.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public void insert(Company record) {
		getSqlMapClientTemplate().insert("companies.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public void insertSelective(Company record) {
		getSqlMapClientTemplate().insert("companies.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Company> selectByExample(CompanyCriteria example) {
		List<Company> list = getSqlMapClientTemplate().queryForList("companies.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public Company selectByPrimaryKey(Integer id) {
		Company key = new Company();
		key.setId(id);
		Company record = (Company) getSqlMapClientTemplate()
				.queryForObject("companies.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Company record, CompanyCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("companies.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public int updateByExample(Company record, CompanyCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("companies.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Company record) {
		int rows = getSqlMapClientTemplate().update("companies.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table companies
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Company record) {
		int rows = getSqlMapClientTemplate().update("companies.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table companies
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends CompanyCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, CompanyCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}