package pe.com.devteam.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.com.devteam.bean.Email;
import pe.com.devteam.bean.EmailCriteria;
import pe.com.devteam.dao.EmailDAO;

public class EmailDAOImpl extends SqlMapClientDaoSupport implements EmailDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public EmailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public int countByExample(EmailCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("emails.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public int deleteByExample(EmailCriteria example) {
        int rows = getSqlMapClientTemplate().delete("emails.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Email key = new Email();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("emails.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public void insert(Email record) {
        getSqlMapClientTemplate().insert("emails.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public void insertSelective(Email record) {
        getSqlMapClientTemplate().insert("emails.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Email> selectByExample(EmailCriteria example) {
        List<Email> list = getSqlMapClientTemplate().queryForList("emails.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public Email selectByPrimaryKey(Integer id) {
        Email key = new Email();
        key.setId(id);
        Email record = (Email) getSqlMapClientTemplate().queryForObject("emails.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Email record, EmailCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("emails.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public int updateByExample(Email record, EmailCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("emails.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Email record) {
        int rows = getSqlMapClientTemplate().update("emails.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Email record) {
        int rows = getSqlMapClientTemplate().update("emails.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table emails
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends EmailCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, EmailCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}